name: Build RDXplorer Snapshot

on:
  push:
    branches: [ "build" ]
    paths:
    - RDXplorer/**
  pull_request:
    branches: [ "build" ]
    paths:
    - RDXplorer/**
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]

    runs-on: windows-latest

    env:
      Project_Name: RDXplorer
      Release_Name: RDXplorer (Snapshot)
      Release_Body: "RDXplorer snapshot release"
      Asset_Name: rdxplorer-snapshot
      
    steps:
    - name: Generate version
      id: version
      uses: amitsingh-007/next-release-tag@v4.2.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ''
        tag_template: 'yyyy.mm.dd.i'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install dependencies
      run: dotnet restore ${{ env.Project_Name }}
      
    - name: Build release
      run: dotnet build ${{ env.Project_Name }} -c Release --no-restore
      
    - name: Publish release
      run: dotnet publish ${{ env.Project_Name }} -c Release -o .\publish --no-restore --no-build
      
    - name: Create zip
      run: Compress-Archive -Path .\publish\* -Destination release.zip

    - name: Upload zip to release
      uses: svenstaro/upload-release-action@v2
      with:
        file: ./release.zip
        asset_name: ${{ env.Asset_Name }}-${{ steps.version.outputs.next_release_tag }}.zip
        release_name: ${{ env.Release_Name }} (${{ steps.version.outputs.next_release_tag }})
        body: ${{ env.Release_Body }} ${{ steps.version.outputs.next_release_tag }}
        tag: ${{ steps.version.outputs.next_release_tag }}
        overwrite: true
